In [1]:
pip install qsimov-Mowstyl

Note: you may need to restart the kernel to use updated packages.


In [2]:
import qsimov as qj

In [3]:
r = qj.QRegistry(2)

In [4]:
s = qj.QSystem(2)

In [5]:
r.get_state()

array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [6]:
s.get_state()

array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [7]:
r2 = r.apply_gate("H",targets=0)

In [8]:
s2 = s.apply_gate("H",targets=0)

In [9]:
r2.get_state()

array([0.70710678+0.j, 0.70710678+0.j, 0.        +0.j, 0.        +0.j])

In [10]:
s2.get_state()

array([0.70710678+0.j, 0.70710678+0.j, 0.        +0.j, 0.        +0.j])

In [11]:
del r
del s

In [12]:
r.get_state()

NameError: name 'r' is not defined

In [ ]:
r2.get_state()

In [13]:
r3 = r2.apply_gate("X",targets=1,controls=0)

In [14]:
r3.get_state()

array([0.70710678+0.j, 0.        +0.j, 0.        +0.j, 0.70710678+0.j])

In [15]:
r3.measure({0,1})

(<qsimov.structures.qregistry.QRegistry at 0x1e45312a050>, [False, False])

In [16]:
r3.measure({0,1})[0].get_state()

error: NULL pointer to registry

In [17]:
import random as rnd

In [18]:
rnd.random()

0.8028386545301998

In [19]:
r3.measure({0,1},random_generator=rnd.random)

(<qsimov.structures.qregistry.QRegistry at 0x1e42a28a490>, [True, True])

In [20]:
import numpy as np

np.random.seed(6470)

In [21]:
r3.measure({0,1},random_generator=rnd.random)

(<qsimov.structures.qregistry.QRegistry at 0x1e45435cf50>, [False, False])

In [22]:
r3.measure({0},random_generator=rnd.random)

(<qsimov.structures.qregistry.QRegistry at 0x1e4536ae790>, [True, None])

In [23]:
r3.measure({0})[0].measure({1})

(<qsimov.structures.qregistry.QRegistry at 0x1e454556490>, [None, False])