In [251]:
import numpy as np

class QRegistry:
    def __init__(self,nqubits):
        self.nqubits = nqubits
        self.estado = np.append(np.array([1],dtype=complex),np.array([0 for _ in range(2**self.nqubits - 1)],dtype=complex)).reshape(-1,1)

    def ket(self):
        return self.estado
    
    def bra(self):
        return np.conjugate(np.transpose(self.estado))
    
    def M_densidad(self):
        return np.dot(self.ket(),self.bra())
    
    def aplicar_puerta1(self, puerta):
        self.estado = np.dot(puerta,self.ket())
        return self.estado
    
    def aplicar_puerta(self, puerta, qubit):
        if qubit == 0:
            operacion = np.kron(np.eye(2**(self.nqubits - 1)),puerta)
        elif qubit == self.nqubits-1:
            operacion = np.kron(puerta,np.eye(2**qubit))
        else:
            operacion = np.kron(np.kron(np.eye(2**qubit),puerta),np.eye(2**(self.nqubits - qubit - 1)))

        self.estado = np.dot(operacion,self.ket())
        #print(operacion)
        return self.estado
    
    def medir(self, qubit):
        lista = [j for j in range(2**self.nqubits) if j//2**(qubit)%2]
        # print(lista)
        r = np.random.rand()
        p = sum(np.absolute(self.estado[i,0])**2 for i in lista)

        if r < p:
            #print("Mide 1")
            listadg = [j for j in range(2**self.nqubits) if j//2**(qubit)%2 == 0]
            for i in listadg:
                self.estado[i,0] = 0
            self.estado = self.estado/np.sqrt(p)
        else:
            #print("Mide 0")
            for i in lista:
                self.estado[i,0] = 0
            self.estado = self.estado/np.sqrt(1-p)

        return int(r < p)


In [269]:
registro = QRegistry(3)
hadamard = 1/np.sqrt(2)*np.array([[1,1],[1,-1]],dtype=np.float128)
registro.aplicar_puerta(hadamard,0)
registro.aplicar_puerta(hadamard,1)
registro.aplicar_puerta(hadamard,2)
registro.aplicar_puerta(hadamard,0)
registro.aplicar_puerta(hadamard,1)
registro.aplicar_puerta(hadamard,2)

array([[1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]], dtype=complex256)

In [252]:
registro = QRegistry(3)
registro.medir(1)

0

In [253]:
ket0 = QRegistry(2)
ket0.ket()

array([[1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [254]:
ket0.bra()

array([[1.-0.j, 0.-0.j, 0.-0.j, 0.-0.j]])

In [255]:
ket0.M_densidad()

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [256]:
registro = QRegistry(1)
hadamard = 1/np.sqrt(2)*np.array([[1,1],[1,-1]])
registro.aplicar_puerta1(hadamard)

array([[0.70710678+0.j],
       [0.70710678+0.j]])

In [257]:
ket0.aplicar_puerta(hadamard,qubit=1)

array([[0.70710678+0.j],
       [0.        +0.j],
       [0.70710678+0.j],
       [0.        +0.j]])

In [258]:
ket0.medir(1)

1

In [259]:
ket0.ket()

array([[0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j]])