In [102]:
import numpy as np

class estado:
    def __init__(self,dimension):
        self.dimension = dimension
        self.estado = np.append(np.array([1],dtype=complex),np.array([0 for _ in range(2**self.dimension - 1)],dtype=complex)).reshape(-1,1)

    def ket(self):
        return self.estado
    
    def bra(self):
        return np.conjugate(np.transpose(self.estado))
    
    def M_densidad(self):
        return np.dot(self.ket(),self.bra())
    
    def aplicar_puerta1(self, puerta):
        self.estado = np.dot(puerta,self.ket())
        return self.estado
    
    def aplicar_puerta(self, puerta, qubit):
        if qubit == 0:
            operacion = np.kron(puerta,np.eye(2**(self.dimension - 1)))
        elif qubit == self.dimension-1:
            operacion = np.kron(np.eye(2**qubit),puerta)
        else:
            operacion = np.kron(np.kron(np.eye(2**qubit),puerta),np.eye(2**(self.dimension - qubit - 1)))

        self.estado = np.dot(operacion,self.ket())
        return self.estado
    
    def medir(self, qubit):
        print([j for j in range(2**self.dimension) if j//2**(qubit)%2 == 1])


In [103]:
ket0 = estado(2)
ket0.ket()

array([[1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [104]:
ket0.bra()

array([[1.-0.j, 0.-0.j, 0.-0.j, 0.-0.j]])

In [105]:
ket0.M_densidad()

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [106]:
registro = estado(1)
hadamard = 1/np.sqrt(2)*np.array([[1,1],[1,-1]])
registro.aplicar_puerta1(hadamard)

array([[0.70710678+0.j],
       [0.70710678+0.j]])

In [107]:
ket0.aplicar_puerta(hadamard,qubit=0)

array([[0.70710678+0.j],
       [0.        +0.j],
       [0.70710678+0.j],
       [0.        +0.j]])

In [112]:
registro = estado(4)
registro.medir(1)

[2, 3, 6, 7, 10, 11, 14, 15]
